name: Backend CI

on:
  push:
    branches: ["main", "master", "dev", "feat/**"]
  pull_request:
    branches: ["main", "master", "dev"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Backend CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Upgrade pip
        working-directory: backend
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
          # Ensure Ruff is available even if not in requirements
          python -m pip install ruff

      # ---------- Ruff ----------
      - name: Ruff – lint (with GitHub annotations)
        working-directory: backend
        run: |
          # Uses pyproject.toml if present; otherwise Ruff defaults
          python -m ruff check . --output-format=github --no-cache --show-fixes

      - name: Ruff – format check
        working-directory: backend
        run: |
          python -m ruff format --check .

      # - name: Lint (flake8 if available)
      #   working-directory: backend
      #   run: |
      #     if python -m flake8 --version >/dev/null 2>&1; then python -m flake8 .; fi

      # - name: Type check (mypy if available)
      #   working-directory: backend
      #   run: |
      #     if python -m mypy --version >/dev/null 2>&1; then python -m mypy .; fi
